version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/nykaa
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build: ./my-nykaa-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nykaa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
